language: python

cache:
  directories:
  - "~/.platformio"

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
            - cmake
            - lcov


install:
- pip install -U platformio
- gem install coveralls-lcov
- export GENERATE_COVERAGE=1

env:
- BOARD=uno
- BOARD=leonardo
- BOARD=megaatmega2560
- BOARD=due
- BOARD=nanoatmega328
- BOARD=nanoatmega168
- BOARD=zero
- BOARD=micro

script:
- set -eo pipefail;
  for e in examples/*; do
    platformio ci --board=$BOARD --lib=. $e/*;
  done

after_success:
    - |
        if [ "${GENERATE_COVERAGE}" ]; then
            # Generate code coverage information & send to Coveralls
            lcov --gcov-tool $GCOV --directory . --capture --output-file coverage.info
            lcov --gcov-tool $GCOV --remove coverage.info 'test/*' '/usr/*' 'external/*' --output-file coverage.info
            lcov --list coverage.info
            coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info
        fi

notifications:
    email: false